name: Development PR

on:
  pull_request:
    branches: ['main']
    paths:
      - src/**
      - index.js
      - app.config.ts
      - package.json
      - assets/**

jobs:

  update:
    name: Publish development update
    type: update
    environment: development
    params:
      platform: all
      channel: development
      message: "PR #${{ github.event.pull_request.number }}"
      